services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=my_spring_data'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '33068:3306/tcp'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - mysql8_data:/var/lib/mysql
volumes:
  mysql8_data: