services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=lab_aop'
      - 'MYSQL_PASSWORD=12345678'
      - 'MYSQL_ROOT_PASSWORD=12345678'
    ports:
      - '33068:3306/tcp'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - mysql8_data:/var/lib/mysql
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  mysql8_data:
  rabbitmq_data: